### ISSUE TITLE
Improving symlinks in `99-outputs`

### ISSUE THREAD

**Issue by lkhilton** [LCR-BCCRC/lcr-modules#123]
Currently, the relative symlinks in `99-outputs` point outside the base module results directory, which means that any time a module's results is moved wholesale the symlinks are broken. Is it possible to either update `op.relative_symlinks` or create a similar function that ensures that symlinks are self-contained within the module results directory?

**Comment by BrunoGrandePhD** [comment]
Out of curiosity, are absolute file paths being provided as input to `op.relative_symlink()`?

I ask this because the function will "relativize" file paths if the the source file path isn't absolute. Oncopipe used to relativize everything (look for `relpath()` in [this diff](https://github.com/LCR-BCCRC/lcr-modules/commit/84d11bc46d1d0c07178ec5e59354d5efeaad9d43#diff-abb31a97733d4b6ab905890020512e791d469549f3644af45cec43e8fa7a916cL139-R149)), but that led to issues elsewhere. I forget what was the issue exactly, but I don't think it had to do with `99-outputs` symlinks. 

A potential way forward is adding a `force_relative` argument to `op.relative_symlink()` that defaults to `False` (_i.e._ current behaviour) but would produce the behaviour you're looking for (I think) if set to True. The only change is that the conditional for [this if-statement](https://github.com/LCR-BCCRC/lcr-modules/blob/master/oncopipe/oncopipe/__init__.py#L224-L226) would be `if not os.path.isabs(src) or force_relative:`. 

The output rules in the module template could be updated accordingly to use this new argument. This would involve updating two lines ([here](https://github.com/LCR-BCCRC/lcr-modules/blob/master/template/%7B%7Bcookiecutter.module_name%7D%7D/1.0/%7B%7Bcookiecutter.module_name%7D%7D.smk#L101) and [here](https://github.com/LCR-BCCRC/lcr-modules/blob/master/template/%7B%7Bcookiecutter.module_name%7D%7D/1.0/%7B%7Bcookiecutter.module_name%7D%7D.smk#L169)). 

If this solution sounds sensible to you, do you mind having a first go at implementing it? I'm a bit behind with work this week. If you do, don't forget to document the new argument in the function docstring. It can be one or two lines describing the argument. Once you open a PR, feel free to request me as a reviewer.

**Comment by lkhilton** [comment]
Thanks, Bruno. No, the paths provided to `op.relative_symlink` are not typically absolute. The fix you suggest does seem straightforward so I will take a stab at updating it and let you know if I run into any issues or when it's ready for review.

**Comment by lkhilton** [comment]
Addressed by #130
