### ISSUE TITLE
switch to conda installation of oncopipe

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#175]
India suggested we should change LCR-modules to use conda to install oncopipe, which should help ensure the dependencies are met. In order to switch to using conda to install oncopipe we need a way to directly create a conda release for any new oncopipe release.

**Comment by oncogenomics** [comment]
It looks like the bioconda release is up to date with our current version (v1.0.11): https://anaconda.org/bioconda/oncopipe
Conda-bot should update within a day or so if we release a new version.
If we use conda to install (rather than pip) when we run lcr-modules we can take advantage of their nice dependency resolution, and optimizations.
I will try running the Bioconda package on Thanos after my meetings today and if it works smoothly I will update the lcr-modules docs.

**Comment by rdmorin** [comment]
Can you determine what date the conda package with that version appeared? I don't think we can assume the lag will only be a few days. We should be certain that it's within an acceptable (ideally consistent) time frame.

**Comment by oncogenomics** [comment]
Laura last updated [the oncopipe version](https://github.com/LCR-BCCRC/lcr-modules/blob/master/oncopipe/oncopipe/__version__.py) on December 5th 2020 and the [oncopipe bioconda package](https://anaconda.org/bioconda/oncopipe) was last updated January 11th 2021.

**Comment by oncogenomics** [comment]
[Here](https://github.com/bioconda/bioconda-recipes/pull/26075) is the update v1.0.11 oncopipe PR on bioconda.

The Conda Bot submits a PR to the bioconda repo (this took roughly 1 month) and then the PR needs to be manually reviewed (roughly 5 days) and merged (0 days).

Skipping the bot and doing a manual PR would have shaved a month off of the update time. We would shave 4 days off by formatting the package with artifacts cleanly included.

**Comment by rdmorin** [comment]
What do you mean by artifacts?

**Comment by oncogenomics** [comment]
[Artifact](https://en.wikipedia.org/wiki/Artifact_(software_development)) is a general software development term. In this case we would need to do small tidying like removing pip install dependencies and replacing them with conda dependencies, and integration with their CircleCI packaging scripts.
