### ISSUE TITLE
Mutect2 edge case error

### ISSUE THREAD

**Issue by emouts** [LCR-BCCRC/lcr-modules#258]
Hello again, I wanted to ask about an issue I encountered when running the mutect2 module.

The checkpoint _mutect2_input_chrs produces an error if input.candidate_positions is empty or only contains headers (pandas.read_csv default behaviour). In my case I was running mutect2 though slms3, with the input set to rules._slms_3_strelka_lofreq_union.output.vcf which was empty for one of our late timepoint samples. 

I was wondering if the desirable behaviour should be that files with no mutations are propagated through to the outputs without halting execution, to avoid the manual step of removing a problematic sample from the sample sheet in order to resume the run. I couldn't think of an easy way to do this without adding several if clauses in all rules from that point onwards, but I am not very experienced with snakemake so there may be a cleaner way.

Thanks again for all your hard work on maintaining this pipeline!

Ilias

**Comment by lkhilton** [comment]
Hi Ilias, 

If I understand correctly, after running this one sample through Strelka and LoFreq, it had no variants called? Have you performed any QC on this sample to see what might be causing this? 

A workaround is to run MuTect2 separately from the SLMS-3 pipeline without specifying the candidate VCF file. However, if Strelka and LoFreq returned empty VCF files, it's unlikely that MuTect2 will find anything either. If this one sample is low quality, it should probably be excluded from your analyses anyway. 

If you really want to try to fix this, you could use Python error handling to catch the empty file ([example](https://stackoverflow.com/a/51230706)) in the checkpoint, and only use it for making the list of chromosomes if it's not empty. Something like: 

```
checkpoint _mutect2_input_chrs:
    input:
        candidate_positions = CFG["inputs"]["candidate_positions"] if CFG["inputs"]["candidate_positions"] else str(rules._mutect2_dummy_positions.output),
        chrs = reference_files("genomes/{genome_build}/genome_fasta/main_chromosomes.txt"),
        capture_arg = _mutect_get_capspace
    output:
        chrs = CFG["dirs"]["inputs"] + "chroms/{seq_type}--{genome_build}/{tumour_id}--{normal_id}--{pair_status}/mutated_chromosomes.txt"
    run:
        # obtain list of main chromosomes
        main_chrs = pd.read_csv(input.chrs, comment='#', sep='\t', header=None)
        main_chrs = main_chrs.iloc[:, 0].astype(str).unique().tolist()
        #obtain list of chromosomes in candidate positions
        try: 
             candidate_chrs = pd.read_csv(input.candidate_positions, comment='#', sep='\t')
             candidate_chrs = candidate_chrs.iloc[:, 0].astype(str).unique().tolist()
        # If the candidate_chrs csv is empty, skip it and initialize candidate_chrs as an empty list
        except pd.errors.EmptyDataError:
            print('Note: filename.csv was empty. Skipping.')
            candidate_chrs = list()
            continue
        # obtain list of chromosomes in the capture space
        interval_chrs = pd.read_csv(input.capture_arg, comment='@', sep='\t')
        interval_chrs = interval_chrs.iloc[:, 0].astype(str).unique().tolist()
        # intersect the three lists to obtain chromosomes present in all
        intersect_chrs = list(set(main_chrs) & set(candidate_chrs) & set(interval_chrs))
        # convert list to single-column df
        intersect_chrs = pd.DataFrame(intersect_chrs).sort_values(0)
        # write out the file with mutated chromosomes
        intersect_chrs.to_csv(output.chrs, index=False, header=False)
```

I probably won't implement this as a permanent solution in the pipeline, however, because this will mean that some samples are handled in SLMS-3 differently, and in reality anything that has zero variants returned from Strelka and LoFreq probably needs to be dropped from the analysis. 

Hope this helps! 
Laura

**Comment by emouts** [comment]
Hi Laura,

Thank you very much for your response, I appreciate it! You are absolutely right that this will only happen on a problematic sample and should be quite rare. My thinking was to avoid manual intervention during a run, but adding workarounds and silently failing can be dengerous too, so keeping it as is makes a lot of sense!

Thanks again,
Ilias
