### ISSUE TITLE
Lofreq- no INDEL calling

### ISSUE THREAD

**Issue by nuttynutmore** [LCR-BCCRC/lcr-modules#273]
Hi there,

Thank you so much for sharing this amazing suite of modules - it has been straightforward to use and easy to add my own downstream analysis modules to.

Something I have noticed is that I see fewer indels than expected in the output from SLMS3 (I am using the 3+ output, similar to your publications).  As I've been going through the outputs of the individual variant calling modules (Strelka, Lofreq, SAGE and Mutect2), I noticed that Lofreq never had any indels in its output.  When I looked more closely at the lofreq.smk files, I found that between rule _lofreq_run_tumour_matched and rule _lofreq_combine_vcf there is a  comment "indels are not yet called but this rule merges the empty indel file with the snvs file to produce consistently named "combined" vcf."

My understanding is that Mutect2 is not set up to run as a de novo variant caller, instead only using input from Strelka and Lofreq.  Therefore, in order for the indels to appear in the final SLMS3 3+ output files, they should be called by Strelka (input from Manta) Lofreq and SAGE.  

I was wondering if there was a particular reason Lofreq is not currently set up to call indels?
If Lofreq is not set to call indels, wont genuine variants get missed from the SLMS3 3+ output? 
What is the benefit of not using Mutect2 to call de novo variants (other than time and computational cost)?  

Many thanks,
Kind regards,
Natasha

**Comment by Kdreval** [comment]
Hi @nuttynutmore ,

Thank you for using our toolset and providing feedback! Happy to hear you found it easy to use in your analysis. We are always happy to answer the questions and explain the decisions we took during the development process.

In regards to the issue of calling indels using SLMS-3, you are right that LoFreq is not set up to call indels. The reason for this is that it cannot do it natively without processing bam files through a specific GATK pipeline that realigns indels and recalibrates base qualities. In addition to this, the indels qualities also have to be added by GATK in order for the LoFreq to call indels properly, and later versions of GATK stopped doing this so we would be required to use older versions that have been discontinued. Therefore, we decided to not call indels with LoFreq. Nevertheless, the genuine variants are still present in the SLMS 3+ final output with a sensitivity of  > 90%. When developing the SLMS-3, we took advantage of using 44 pairs of the FF vs FFPE sample from the same patient, and the approach we took was characterized by very high precision in both FF and FFPE. Please see this plot:
![image](https://github.com/LCR-BCCRC/lcr-modules/assets/47579823/63f16ce0-07ce-4855-9b62-d42ba688ecd0)

Here, the ground truth was any variant called by two or more of Strelka2/LoFreq/Mutect2, so before the introduction of SAGE to the pipeline. For indels, it would have been _very_ lenient Strelka2 indels that were validated by Mutect2, and this plot shows that for the FF samples adding SAGE and keeping it to 2+ variant callers led to a decrease in precision (more stuff called) while 3+ led to _way_ better precision with very little drop in recall. So, the genuine indels are still present in the SLMS 3+ outputs because they are called by Strelka2, validated by Mutect2, and are also independently called by SAGE.  It is also worth adding here that since the time this plot was generated, we have made a modification to the workflow allowing for the clustered variants at aSHM loci to pass through the filters more often.

That being said, if you would prefer to move to a more lenient combination, you can find all the intersect files and which variants were called by which caller in the `slms_3-1.0/starfish-2.0/99-outputs/vcf/{seq_type}--{genome_build}/` folder.

In regards to the benefit of not using Mutect2 to call variants de novo, you are absolutely right that the benefit is the processing time. Even when the candidate positions are supplied and while Mutect2 is parallelized by chromosome, this is still the limiting factor in the whole pipeline, and on some genomes in our experience, it runs for > 48h, so calling the variants de novo was not an option due to the processing time.

We will be happy to provide more details or answer other questions if you have any.

**Comment by nuttynutmore** [comment]
Hi @Kdreval ,

Thank you for your really comprehensive explanation and the suggestion of looking at the more lenient SLMS3 output.

That makes a lot of sense as to why Lofreq isn't used to call indels.  We share you're thoughts on moving away from outdated tools and versions.

The role of Mutect2 is also much clearer to me now.  Interesting that it is still so slow, even when given candidate positions.  We are using a limited capture panel, so I might try using it de novo on one or two files, just to see how long it might take (but I suspect the added benefit vs time taken may not give us as much reward as hoped, given your experience).

Thanks again- you have produced a fantastic package!
Kind regards,
Natasha
