### ISSUE TITLE
Strelka SomaticEVS filtering threshold

### ISSUE THREAD

**Issue by nuttynutmore** [LCR-BCCRC/lcr-modules#277]
Hi there,

Thanks again for the great suite of modules.  

I have noticed I see fewer indels than expected in the output from SLMS3 (I am using the 3+ output, similar to your publications).  Whilst troubleshooting, I see that Strelka's output is filtered by SomaticEVS >10, and this is hardcoded into the SLMS3 snakemake file (rule _slms_3_annotate_strelka_gnomad).  I have read all your publications that refer to SLMS3 and can't find any documentation describing how this threshold was calculated, or if it is a standard threshold set elsewhere.  I have also looked at how EVS is used in other publications and there doesn't seem to be an agreed standard threshold.

I have read Strelka's primary methods manual, paying particular attention to the parts describing the calculation of the SomaticEVS.  My understanding is that this is used as a FILTER metric (LowEVS if SomaticEVS <= 5 for SNVs or <=6 for indels), which then annotates the FILTER column of the output vcf as either "PASS" or "LowEVS".  I see that you also include a filtering step that filters based on this PASS/LowEVS annotation.

I am reluctant to totally remove the SomaticEVS filtering, however, this seems to have the largest impact on recovering the missing indel output for my data. Would you mind explaining why there is the further filtering step using a SomaticEVS >10?  Was this decided based on statistical calculations from your own data and experience, or is this a standard set somewhere else and I'm just being silly and can't find it?

Your insight and experience is greatly appreciated,
Kind regards,
nuttynutmore

**Comment by lkhilton** [comment]
Hey there, 

We chose that threshold in part because a collaborator working on a similar consensus variant calling method found that it was an optimal balance of sensitivity and specificity. We accepted the tradeoff so that we could reduce false positives, especially in FFPE data. We found Strelka2 is a pretty lenient variant caller with default settings and we got a lot of noise with the default filtering in place. 

Do you have examples of particular indels that are recurrently missing in the outputs, or is there no pattern to which indels drop out? Are they called robustly by SAGE? 

Cheers, 
Laura

**Comment by nuttynutmore** [comment]
Hi Laura,

Thank you for those insights- that's really helpful.

Our initial output returned no indels when we used the somaticEVS threshold of 10.  When we remove the threshold filtering, we get indels in the output, some of which are also called by SAGE.  We're currently troubleshooting to find the optimal threshold for our data.

Thanks again for your thoughts and for the great suite of modules.
Kind regards,
Natasha
