### ISSUE TITLE
Manta fails if index files aren't produced simultaneously

### ISSUE THREAD

**Issue by lkhilton** [LCR-BCCRC/lcr-modules#29]
I'm running a RNAseq pipeline where BAMs are aligned with STAR and duplicates are marked with GATK MarkDuplicates. The .bai index files are produced in a subsequent step. Because the Manta module takes only .bam files as input and assumes the .bai indexes exist, Snakemake proceeded to run Manta before the .bai indexes were created, meaning it populated the `00-inputs` directory with dead symlinks for the .bai files. To ensure this doesn't happen, should the .bai files be specified as inputs to the Manta module?

**Comment by BrunoGrandePhD** [comment]
Oups, I got lazy with the input rule. I hesitate to add a user-configurable input file for the BAM index because they could be in different directories if used by a madman/madwoman. I think the following should fix the issue, since it will trigger Snakemake to wait for the BAI files to be created. Let me know if this solves your issue. 

```
rule _manta_input_bam:
    input:
        sample_bam = CFG["inputs"]["sample_bam"],
        sample_bai = CFG["inputs"]["sample_bam"] + ".bai"
    output:
        sample_bam = CFG["dirs"]["inputs"] + "bam/{seq_type}--{genome_build}/{sample_id}.bam",
        sample_bai = CFG["dirs"]["inputs"] + "bam/{seq_type}--{genome_build}/{sample_id}.bam.bai"
    run:
        md.symlink(input.sample_bam, output.sample_bam)
        md.symlink(input.sample_bai, output.sample_bai)
```

**Comment by lkhilton** [comment]
Looks perfect, thanks!

**Comment by BrunoGrandePhD** [comment]
Scratch that. 

Because inputs like `CFG["inputs"]["sample_bam"]` can be functions, I can't just use `+ ".bai"`. I think @lkhilton's original suggestion is better. And I just realized now that the potential issue where the BAM and BAI files are separated is a non-issue, since I symlink them next to one another anyways. This will be fixed in an upcoming release.
