### ISSUE TITLE
Automatic cram-to-bam for compressed bam files

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#42]
We will inevitably start encountering cram-compressed genomes during GAMBL and other projects. It would be wonderful if we had a standard rule or module that would handle this scenario. If it was an optional module, then anyone encountering a cram could add it when necessary. I envision the functionality being:
1) decompress to bam in scratch directory
2) regenerate index for bam
3) symlink as usual as per the first step in a lcr pipeline
4) optionally remove the bam after all steps in the workflow that rely on that bam have completed

**Comment by BrunoGrandePhD** [comment]
There are a few ways this could be tackled. For GAMBL, I think the simplest solution is to handle this outside of lcr-modules. One idea is to create a directory in `results/` (which is scratch space) where the BAM files are symlinked and the CRAM files are decompressed, _e.g._ `results/data_bams/`. This way, lcr-modules doesn't need to conditionally handle samples stored as CRAMs. All it knows is that there is a single source for all BAM files. 

For example, let's say you have two RNA-seq BAMs, but one is CRAM-compressed. 
```
data
├── sample_A.bam
├── sample_A.bam.bai
├── sample_B.cram
└── sample_B.cram.crai
```

You would have two rules in your project snakefile: one to decompress CRAM files into `results/data_bams/` and another to symlink BAM files into `results/data_bams/`. And you can use `temp()` in the decompression rule to have the decompressed BAM files be automatically deleted once the modules are done with them. With these rules, instead of setting `sample_bam` in lcr-modules to `data/.../{sample_id}.{genome_build}.bam`, you would set it to `results/data_bams/.../{sample_id}.{genome_build}.bam`. 
```
rule cram_to_bam:
    input: 
        cram = "data/{data_subdir}/{file_name}.cram"
    output: 
        bam = temp("results/data_bams/{data_subdir}/{file_name}.bam"),
        bai = temp("results/data_bams/{data_subdir}/{file_name}.bam.bai")
    shell:
        "samtools view -b {input.cram} > {output.bam} && samtools index {output.bam}"

rule bam_to_bam:
    input: 
        bam = "data/{data_subdir}/{file_name}.bam",
        bai = "data/{data_subdir}/{file_name}.bam.bai"
    output: 
        bam = "results/data_bams/{data_subdir}/{file_name}.bam",
        bai = "results/data_bams/{data_subdir}/{file_name}.bam.bai"
    shell:
        "ln -srf {input.bam} {output.bam} && ln -srf {input.bai} {output.bai}"
```

After running these rules, you would end up with this:
```
data
├── sample_A.bam
├── sample_A.bam.bai
├── sample_B.cram
└── sample_B.cram.crai
results/data_bams
├── sample_A.bam -> ../data/sample_A.bam
├── sample_A.bam.bai -> ../data/sample_A.bam.bai
├── sample_B.bam (will be deleted when no longer needed)
└── sample_B.bam.bai (will be deleted when no longer needed)
```

What do you think of this approach?

**Comment by rdmorin** [comment]
This sounds reasonable. Is this something we could put into a template project snakefile similar to the demo but meant as a "starting point" for peoples projects? This would be similar to what you and @lkhilton implemented for gambl.

**Comment by BrunoGrandePhD** [comment]
Yeah, this could be something that is added to the header snakefile I created. 

https://github.com/morinlab/gambl/blob/bgrande-unix_group/src/snakemake/header.smk
