### ISSUE TITLE
obtain input files that are stored remotely as local tempfiles 

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#54]
Within the lcr-modules approach, is there a way to obtain a temporary copy of input files on-the-fly? For example, if bam files are stored on a remote file system that cannot be mounted? This situation can occur when working in AWS.

**Comment by BrunoGrandePhD** [comment]
As long as the the input file is configurable under `CFG["inputs"]`, it should be possible without changing the module snakefile using the "Remote files" feature in Snakemake. That said, I haven't tested this yet. 

https://snakemake.readthedocs.io/en/stable/snakefiles/remote_files.html

This would be an instance of updating configuration values (in this case, of `inputs`) within the snakefile. 

https://lcr-modules.readthedocs.io/en/latest/for_users.html#within-the-snakefile

**Comment by rdmorin** [comment]
I have tested that on AWS and sadly it only works if you have pretty extensive permissions on the bucket you are pulling the remote file from. The one I tried gave me a fatal error. My workaround was to write a rule that pulled the files using the aws CLI.

**Comment by rdmorin** [comment]
To clarify, the problem is that the approach I was using in another Snakefile doesn't seem compatible with lcr-modules (or I haven't figured out how to make it work similarly) because my snakefile always seems to check for all the input files when it runs.

**Comment by BrunoGrandePhD** [comment]
Whatever you did in the other Snakefile should be possible in lcr-modules. If you have a rule `pull_file` that downloads the remote file when needed, when you can point the `inputs` of a module to the output of that rule, thus triggering the download when the module needs that file.

**Comment by rdmorin** [comment]
My approach before included limiting to an artificial "bam" resource value of 2. How do you suggest I modify the first rule to ensure only the bam from the tumour and matched normal are obtained in sync? Will it naturally follow the order in the metadata? 
```
rule _battenberg_input_bam:
    input:
        bam = CFG["inputs"]["sample_bam"],
        bai = CFG["inputs"]["sample_bai"]
    output:
        bam = CFG["dirs"]["inputs"] + "bam/{seq_type}--{genome_build}/{sample_id}.bam",
        bai = CFG["dirs"]["inputs"] + "bam/{seq_type}--{genome_build}/{sample_id}.bam.bai"
    run:
        op.relative_symlink(input.bam, output.bam)
        op.relative_symlink(input.bai, output.bai)

**Comment by BrunoGrandePhD** [comment]
I didn't appreciate that there was also a limitation on the number of remote BAM files that could be stored locally. This is rather an unusual setup, but it should still be possible to accommodate it in lcr-modules. One reason that I always had in the back of my mind for the simple input rules is that they make it easy to override how files are brought into the module. 

For example, let's say you have a `pull_bam` rule that downloads the BAM/BAI files. You can configure the rule to be able to output in the `00-inputs` directory of any module (see rule below). On its own, this would lead to `AmbiguousRuleException` errors, because more than one rule (_i.e._ `_battenberg_input_bam` and `pull_bam`) can produce the same file. You can circumvent this using the `--allow-ambiguity` command-line option, which will force Snakemake to default to the first of the ambiguous rule. So, as long as `pull_bam` is before the point you include the modules, this should work. 

```python
rule pull_bam:
    output:
        bam = "results/{subdir}/00-inputs/bam/{seq_type}--{genome_build}/{sample_id}.bam",
        bai = "results/{subdir}/00-inputs/bam/{seq_type}--{genome_build}/{sample_id}.bam.bai"
    resources:
        bam = 1
    shell:
        command to download files
```

**Comment by rdmorin** [comment]
Thanks for the tip. Out of interest, why would we make the target the same place the symlinks point rather than make it the file that is the input expected by _battenberg_input_bam ? I would think this would overcome the ambiguous rule/target issue. 
Is this to avoid broken symlinks later?

**Comment by rdmorin** [comment]
Presumably the first bit should look like this, right?
```
rule pull_bam:
    output:
        bam = temp("results/{subdir}/00-inputs/bam/{seq_type}--{genome_build}/{sample_id}.bam"),
        bai = temp("results/{subdir}/00-inputs/bam/{seq_type}--{genome_build}/{sample_id}.bam.bai)"
    resources:
        bam = 1

**Comment by rdmorin** [comment]
Using this approach I get the following error

WorkflowError:
Target rules may not contain wildcards. Please specify concrete files or a rule without wildcards.

```
rule fetch_bam:
    output:
        bam = temp("results/battenberg-1.0/00-inputs/bam/genome--{genome_build}/{sample_id}.bam"),
        bai = temp("results/battenberg-1.0/00-inputs/bam/genome--{genome_build}/{sample_id}.bam.bai")
    resources:
        bam = 1
    shell:
        'aws s3 cp {params.bucket}/{wildcards.sample_id}.bam {output.bam}'
	'aws s3 cp {params.bucket}/{wildcards.sample_id}.bam.bai {output.bai}'

**Comment by BrunoGrandePhD** [comment]
Indeed, the `fetch_bam` rule should be using `temp()`. 

As for your first question, if the `fetch_bam` rule (using `temp()`) is upstream of the `_battenberg_input_bam` rule, I think the BAMs would get auto-deleted by snakemake after the `_battenberg_input_bam` symlinking is done, because as far as snakemake is concerned, the output of `fetch_bam` is no longer needed. I thought of using hard links instead, but this would require updating `_battenberg_input_bam` to use a `bam` resource. 

As for your error, this is usually caused by having a non-target rule (_i.e._ a rule with wildcards) as the first rule in your snakefile. You can avoid this by creating a rule `all` as the first rule in your snakefile, or by explicitly requesting specific files at the end of the snakemake command. For example, I have a `_strelka_all` target that I specify at the end of the following command:

```
nice snakemake --profile numbers --restart-times 3 --keep-going _strelka_all
```

**Comment by rdmorin** [comment]
Do you think we should avoid having a bam resource in modules?

**Comment by BrunoGrandePhD** [comment]
It's something that I've considered before. For the time being, I've refrained from using a `bam` resource for two reasons. First, BAM files can vary wildly in size within a project, so it's a really rough way of limiting disk usage. Second, there are other ways of limiting disk usage. (Notably, by using scratch directories and/or by running jobs in [batches](https://snakemake.readthedocs.io/en/stable/executing/cli.html#dealing-with-very-large-workflows).) Also, I've been wanting to implement a function that can estimate the disk usage based on the input file size. This would be a more accurate solution, because the user could just specify the actual disk space in GB (rather than using a rough estimate number of BAMs).

In this case, the `_battenberg_input_bam` rule isn't creating a BAM file (just a symlink), so I don't think it should be using a `bam` resource in the module anyways. On the other hand, your `fetch_bam` rule, which overrides the `_battenberg_input_bam` rule, does create a BAM file, and thus it makes sense to specify a `bam` resource.

**Comment by rdmorin** [comment]
My workaround was a bit more involved. To avoid the "missing" input files, I started by (outside Snakemake) touching an empty file for each of the inputs in the original data directory. The fetch_bam rule uses these as input merely to get the wildcard. I had to make this rule process both the tumour and matched normal together to ensure the subsequent steps get both bams. Otherwise, each bam came through at (semi) random. 

```
bam_bucket_1 = "s3://aws/s3/bucket/where/the/bams/are"

rule fetch_bam:
    input:
        fake_tumour = "data/{patient_id}-T.bam",
	fake_normal = "data/{patient_id}-N.bam"
    output:
        tbam = temp("results/battenberg-1.0/00-inputs/bam/genome--hg38/{patient_id}-T.bam"),
        tbai = temp("results/battenberg-1.0/00-inputs/bam/genome--hg38/{patient_id}-T.bam.bai"),
	nbam = temp("results/battenberg-1.0/00-inputs/bam/genome--hg38/{patient_id}-N.bam"),
        nbai = temp("results/battenberg-1.0/00-inputs/bam/genome--hg38/{patient_id}-N.bam.bai")
    resources:
        bam = 2
    params: bucket=bam_bucket_1
    shell:
        'aws s3 cp {params.bucket}/{wildcards.patient_id}-T.bam {output.tbam} && '
	'aws s3 cp {params.bucket}/{wildcards.patient_id}-T.bam.bai {output.tbai} && '
	'aws s3 cp {params.bucket}/{wildcards.patient_id}-N.bam {output.nbam} && '
	'aws s3 cp {params.bucket}/{wildcards.patient_id}-N.bam.bai {output.nbai}  '

**Comment by BrunoGrandePhD** [comment]
Snakemake should be able to create those output files _de novo_ (_i.e._ without input files). Can you try this rule without the input files? Snakemake uses the output files for inferring the wildcards, not the input files. This would obviate the need of creating those empty files. If you run into a missing input files error, you can send me your entire Snakefile privately so I can take a look. 

```
bam_bucket_1 = "s3://aws/s3/bucket/where/the/bams/are"

rule fetch_bam:
    output:
        tbam = temp("results/battenberg-1.0/00-inputs/bam/genome--hg38/{patient_id}-T.bam"),
        tbai = temp("results/battenberg-1.0/00-inputs/bam/genome--hg38/{patient_id}-T.bam.bai"),
	nbam = temp("results/battenberg-1.0/00-inputs/bam/genome--hg38/{patient_id}-N.bam"),
        nbai = temp("results/battenberg-1.0/00-inputs/bam/genome--hg38/{patient_id}-N.bam.bai")
    resources:
        bam = 2
    params: 
        bucket=bam_bucket_1
    shell:
        'aws s3 cp {params.bucket}/{wildcards.patient_id}-T.bam {output.tbam} && '
	'aws s3 cp {params.bucket}/{wildcards.patient_id}-T.bam.bai {output.tbai} && '
	'aws s3 cp {params.bucket}/{wildcards.patient_id}-N.bam {output.nbam} && '
	'aws s3 cp {params.bucket}/{wildcards.patient_id}-N.bam.bai {output.nbai}  '
```

**Comment by rdmorin** [comment]
Hah. You're right. It works without the inputs. I had erroneously added these when I had another error complaining about missing inputs but moving this rule into the module fixed that issue. I have just realized that the original error was because I had put this fetch_bam rule before "all". Putting it after that rule in Snakefile seems to work.

**Comment by BrunoGrandePhD** [comment]
Excellent!
