### ISSUE TITLE
Provide other common resources for more restrictive schedulers

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#70]
Some schedulers impose a default time constraint on jobs that can be quite short. For example, my jobs on Cedar (Westgrid) seem to be given a limit of 60 minutes. We should either provide a wrapper that requests a much longer/realistic time for jobs or incorporate this into the rules for all non-local jobs. We may have to address this for other limits also.

**Comment by BrunoGrandePhD** [comment]
Currently, resources (mainly `mem_mb` for now) are listed individually in the module snakefile ([example](https://github.com/LCR-BCCRC/lcr-modules/blob/master/modules/manta/2.3/manta.smk#L139-L141)). Because of this, custom resources need to be added to the snakefiles. 

In order words, there is no way of adding custom resources on a per-rule basis by simply editing the YAML configuration file. That said, I think this can easily be implemented. 

The key here is to leverage the ability for snakemake to expand python dictionaries to take in key-value pairs. This functionality is best demonstrated with [`unpack()`](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#input-functions-and-unpack). However, when no functions are involved, you can simply use the Python unpacking operator, `**`. I was able to confirm that this works for the `resources` directive. 

Here was my test snakefile:
```python
custom_resources = {"mem_mb": 1500, "walltime": 24}

rule test_rule:
    output: "output.txt"
    threads: 2
    resources: **custom_resources
    # Thanks to unpacking, the above line is equivalent to:
    # resources:
    #     mem_mb: 1500
    #     walltime: 24
    shell: "echo Threads: {threads} / Resources: {list(resources.keys())} > {output}"
```

After running the rule, `output.txt` contained `Threads: 2 / Resources: 2 1 1500 24`. Normally, you would refer to a specific resource (_e.g._ `{resource.mem_mg}`), but here, I wanted to see everything tracked as a resource. Note that the first two numbers are internally tracked resources, `_cores` and `_nodes`, which we can ignore here. 

Given this functionality, I propose that future modules stop using the `mem_mb` field in the configuration YAML file and start using a `resources` field. Under this new field, there would be keys for each rule (like `mem_mb`), but the values paired with these keys would be a set of key-value pairs instead of integers. 

Let's take the manta-2.3 module as an example. The default configuration file would change as follows. Note that I took the liberty to move the `bam` resource from the Snakefile to the YAML file since this new format can now handle an arbitrary number of resources. 

```
lcr-modules:
    manta:
        [...]

        # Before
        mem_mb:
            manta: 6000
            augment_vcf: 2000
            vcf_to_bedpe: 2000

        # After
       resources:
            manta: 
                mem_mb: 6000
                bam: 1
            augment_vcf: 
                mem_mb: 2000
            vcf_to_bedpe: 
                mem_mb: 2000
```

Once the configuration file is updated, the only other thing that needs to change is the `resources` directives in the snakefile: (1) add the unpacking operator (`**`), and (2) switch the `mem_mb` key to `resources`. And with this, you should have completely configurable resources. 
```
rule _manta_run:
    [...]

    # Before
    resources: 
        mem_mb = CFG["mem_mb"]["manta"],
        bam = 1

    # After
    resources: **CFG["resources"]["manta"]
```

The one drawback of this approach is that additional work will be required to mix the resources specified in the configuration file and resource functions (like the `op.retry()` function that auto-increases memory). I have ideas on how to overcome this (and possibly automatically make every `mem_mb` resource as an auto-increasing one.

**Comment by rdmorin** [comment]
I have added a shell script "snakemake.slurm.sh" that allows users to launch snakemake on a Slurm cluster and currently sets the default job walltime to 8 hours. Lots of room for improvement still.

**Comment by Kdreval** [comment]
This is now implemented throughout with resource unpacking from config of the corresponding module
