### ISSUE TITLE
Demo workflow does not consistently run to completion

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#91]
Due to ongoing development the demo keeps getting broken. If nothing else works in lcr-modules at least the demo needs to work consistently.

**Comment by whelena** [comment]
Are there any specific issues that consistently comes up (specific modules or rules)?

**Comment by whelena** [comment]
It seems like it's missing some inputs (e.g. `99-20595T.bam`) since the sample_id is in the `samples.tsv` but it seems like you are using it to test specific modules only. I'm familiar with the original demo bam files, but I'm wondering which modules uses the igv.seg files.

would it be possible to get samples that can be used with all the modules to limit the number of samples in the samples.tsv?

**Comment by rdmorin** [comment]
Kostia's currently working on this. I think he has an updated version in a branch too.

**Comment by whelena** [comment]
Okay! I'll be available if he needs any help

**Comment by Kdreval** [comment]
I just pushed the version of demo workflow that I was able to complete in dry run and on cluster to the branch demo_repairs
